// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.asistp.domain;

import com.asistp.domain.Worker;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Worker_Roo_Configurable {
    
    declare @type: Worker: @Configurable;
    
}
